### ISSUE TITLE
src/verb/geom/Intersect.hx:3: characters 7-21 : Class not found : promhx.Promise

### ISSUE THREAD

**Issue by scottstensland** [pboyer/verb#10]
I am trying to install verb   (long time developer though new to haxe + verb)

... just installed haxe  (version 1:3.0.0~svn6707-4 ) on ubuntu  14.10

then successfully installed these two haxe libraries 

haxelib install promhx
You already have promhx version 1.0.17 installed

haxelib install nodejs
Current version is now 2.2.6

git clone https://github.com/pboyer/verb.git

cd ~/other_src/verb

npm install .

which installed node modules OK

here is the error 

grunt build
Running "haxe:hxml" (haxe) task

Building Haxe project... 
buildjs.hxml
src/verb/geom/Intersect.hx:3: characters 7-21 : Class not found : promhx.Promise
Fatal error: Error

...  after doing some digging I am correctly finding that haxe library I believe as per command 

haxelib path promhx

/home/stens/haxe/lib/promhx/1,0,17/
-D promhx

Any advice would be appreciated ... cheers Scott Stensland

**Comment by pboyer** [comment]
Hi @scottstensland,

Please check out for verbnurbs.com/docs for more info. This should be fixed.
