### ISSUE TITLE
If I found a mistake, but am not familiar enough with haxe, what do I do?

### ISSUE THREAD

**Issue by ParametricStandarization** [pboyer/verb#12]
The

verb.core.Modify.curveReverse

return new verb.core.types.NurbsCurveData(curve.degree(),verb.core.Modify.knotsReverse(curve.knots()),verb.core.ArrayExtensions.reversed(curve.controlPoints()));

was missing all the "()" after the call to the functions (curve.degree() was curve.degree)

would like to help, but need a serious help on how to work in haxe,

Greetings.

**Comment by ParametricStandarization** [comment]
next to that, an arc won't allow to be reversed with this piece of code

**Comment by pboyer** [comment]
verb is in a moment of upheaval at the moment.

* I plan to make many things better documented when I can get around to it.  verbnurbs.com is painfully out of date.  Once I finish polyhedral brep booleans I plan on doing another release (0.1.0).

* I can't teach you Haxe, but there are plenty of resources out there for that.  Try google.  If you don't already know JavaScript, it might be slow-going.

* I'd highly recommend downloading IntelliJ IDEA if your looking to develop for verb in haxe.  This will give you autocomplete and various kinds of static analysis you might find in other statically typed languages.  

* You'll also find many examples of using the code in `examples` directory in JS/HTML.  The unit tests in `tests/test.js` cover the entire API with examples.

**Comment by pboyer** [comment]
For the kind of development you're doing, I'd recommend using the object oriented api.  Look at src/verb/geom/NurbsCurve.hx.

```
var c = new verb.geom.Arc([0,0,0], [1,0,0], [0,1,0], 5, 0, Math.PI/ 2 );
var cr = c.reverse(); 
```

**Comment by ParametricStandarization** [comment]
I seem to be getting my way around in your library. I noticed that your website is way out of date, but that does not bother me.
Wat bothers me is that I do know Javascript (although I’m a self tought ugly coding basterd), and I am definitly able to read your haxe files.
I would just like it so much if there would be a “one, two ,three” step example how to build the haxe files.

Because I’m more a designer (as in product designer) as opposed to hardcore coder, I’m not good a programmer enough to understand the explanation you give in your read me (I’m sorry for that).

But well. Giving the tip for the IDE is very very nice. Did download flashdevelop, but I get stuck on compiling the stuff.
So now I change the mistakes I find in javascript in the .js file, and when I want to add an object (such as a rectangle, or a trimmed nurbs surface) I code it in my own file or hack something together with the three.js library.

(although am I wrong to think that if you want a polyhedral brep boolean, you need to have the ability for timmed surfaces?)

When I have some time I’ll see to get into the Haxe thing, looks like a real nice coding environment to me.

Jesse

**Comment by ParametricStandarization** [comment]
and that was the one I was trying to use, it refers to that second function, which fails.

**Comment by pboyer** [comment]
I've added an example:

https://github.com/pboyer/verb/blob/master/examples/curveReverse.html

and a unit test for this behavior.  I did not find any issues.  

Just to clarify, `NurbsCurve.reverse` means to reverses the parametric direction of the curve.  Thus, for a curve with a domain from [0,1.0], `curve.point(0)` will end up as `curveReversed.point(1.0)` in the result.  Please reopen if you can give me a concrete failing example in the current code base.
