### ISSUE TITLE
Boolean example is broken

### ISSUE THREAD

**Issue by skbizport** [pboyer/verb#13]
"Verb.hx:56: verb 0.2.0" verb.js:178:202

TypeError: verb.topo.Boolean.split is not a function

**Comment by pboyer** [comment]
Thanks @skbizport!  Right now, this code is still under construction.  It will come alive in the next few months.

**Comment by skbizport** [comment]
Thx.

Any plans of supporting non-planar faces?

Face.hx:
//public var srf : ISurface; // TODO: all faces now planar

Regards
