### ISSUE TITLE
Remarks on verb's docs

### ISSUE THREAD

**Issue by PhiLhoSoft** [pboyer/verb#18]
I just discovered verbs, which looks very interesting!

I explore the documentations, and has some remarks on the form itself, to help you to improve them. :smile:  Writing them as I explore (quickly) the doc.

- Title of the landing page of docs is "Home". Not helpful... Bad for bookmarking. You should take the good title from the home page, prefixed or suffixed with Docs.
- Markdown links in the "_Using with JavaScript_" section are broken (ie. appear as Markdown, not as links).
- Advice: don't use "here" links (eg. in the last paragraph of the above page), link to the whole sentence. That's better for SEO... :wink: 
- http://verbnurbs.com/docs/geom/BezierCurve/ - I like the form, but I see `Array<Point>` (OK), except I can't find `Point` in the drop-down menus of the various modules... I had the idea to look at `Line` which explains what Point is, but I think it is worth a specific entry.
- http://verbnurbs.com/docs/geom/NurbsCurve/ - "_Calling one of these methods returns a Promise that respect the You can find further_" -> looks like there is an unfinished sentence...

Well, I have to stop here, but I will come back to this interesting library later!

**Comment by pboyer** [comment]
Thanks @PhiLhoSoft! These are very helpful comments. I'll take a look soon.

**Comment by cloudcompare** [comment]
Hi, same thing here. I just discovered VERB and it looks pretty impressive.

I noticed a small glitch in the documentation: the link to node.js in the 'Getting started' section points on Haxe website.

**Comment by pboyer** [comment]
Hi friends, 

I made almost all of these changes (see http://verbnurbs.com/docs/), although Point remains under core -> Data : http://verbnurbs.com/docs/core/Data/#point

There are many such types in verb and it would require some kinda painful restructuring to do this right. I'll keep this in mind for the future, though.
