### ISSUE TITLE
Plan about further developing.

### ISSUE THREAD

**Issue by Evil-Spirit** [pboyer/verb#21]
What is about to continue your work?
There is no good open source NURBS.

**Comment by pboyer** [comment]
Hi @Evil-Spirit! I've been pretty busy the last few months, but I should be putting some new features in soon. The `speed` branch is about 10x faster for nearly all computations.

**Comment by Evil-Spirit** [comment]
We want to found something good for the https://github.com/whitequark/solvespace.
