### ISSUE TITLE
Small tolerance intersect surface-curve(1e-3)

### ISSUE THREAD

**Issue by traking** [pboyer/verb#28]
Is it possible, to improved greatly?

**Comment by pboyer** [comment]
Can you give some more context? Is the current algorithm insufficient for your application?

**Comment by traking** [comment]
Tried intersected this suraface http://verbnurbs.com/examples/surface.html and Line(NurbsCurve) when all was well made with tolerance 0.1

**Comment by pboyer** [comment]
Can you copy the code here?

**Comment by traking** [comment]
I'm sorry , it was my error... Thank you:)
