### ISSUE TITLE
Fails with browserify

### ISSUE THREAD

**Issue by uqee** [pboyer/verb#31]
Hi, @pboyer 

In docs you [write](http://verbnurbs.com/docs/) that one can use verb with require.js (AMD) or browserify (commonjs) in the browser or in node.js.

But, doing `require('verb-nurbs')` actually fails with `Uncaught TypeError: exists is not a function` at [`verb#L29`](https://github.com/pboyer/verb/blob/master/build/js/verb.js#L29) -> [`node-webworker-threads#L1`](https://github.com/audreyt/node-webworker-threads/blob/master/index.js#L1) -> [`node-bindings#L55`](https://github.com/TooTallNate/node-bindings/blob/master/bindings.js#L55) -> [`node-bindings#L153`](https://github.com/TooTallNate/node-bindings/blob/master/bindings.js#L153).

Would you provide any suggestions?

**Comment by pboyer** [comment]
@uqee Thanks a lot for letting me know. This should be fixed in 2.0.2 - out now. Just give it a npm install
