### ISSUE TITLE
Return Control points, "CurvebypointsInterpolation"

### ISSUE THREAD

**Issue by Paksuhomo** [pboyer/verb#41]
Hi, 

I'm not 100% sure if this is already possible, but would be great to have function to return control points on interpolated curves

**Comment by dgirardeau** [comment]
Indeed, that's not possible yet.

**Comment by pboyer** [comment]
http://verbnurbs.com/docs/eval/Make/#rationalinterpcurve 

Make.rationalInterpCurve provides what you want. Let me know if you need help.
