### ISSUE TITLE
Intersection Algorithm Documentation + Extensions

### ISSUE THREAD

**Issue by henryJack** [pboyer/verb#43]
Hi,

I've been using verb for a few weeks. I was just wondering if there are any docs for how the intersection algorithm works?

I Am looking at extending this code so you can compute the surface area and volume of intersected regions. Any pointers on this would be great!

Best,
Henry

**Comment by pboyer** [comment]
This is the best place to start. Sorry I didn't see this earlier! http://verbnurbs.com/docs/eval/Intersect/ You can click on the individual methods to read the code.

**Comment by pboyer** [comment]
https://github.com/pboyer/verb/blob/master/src/verb/eval/Intersect.hx/#L49 Here's something a bit more specific for surface intersection.
