### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by gedw99** [pboyer/verb#7]
awesome to see nurbs being developed for javascript.
i use grasshopper and used to use nuke and flame and flint. all node based tools.

i am using a different rendering engine. OSGJS. i used to use three. i am thinking of forking but dont want to split things as frankly the nurbs does my head in. BTW there is no real standard for what  nurbs is from what i could see. Its not interoperable. Mckneel have theirs that they call open nurbs, and its not open. Mhh.. Cad world is very closed.

so i was wondering if the nurbs data flow can be separated from the rendering engine ? it will also help make testing much easier..

**Comment by pboyer** [comment]
Yes, the rendering is explicitly separated from rendering.  

You'll find tools for NURBS tessellation in verb, but nothing having to do with WebGL or anything like that.  It's a client dev's responsibility to do all of that sort of stuff.  There's examples using three.js in the examples folder.
