### ISSUE TITLE
Quality difference between two HTML examples, no way to display/hide triangles easily.

### ISSUE THREAD

**Issue by nmz787** [pboyer/verb#9]
I note that using the threeMeshIntersectExample.html style for drawing/rendering/viewing seems more chunky and less smooth than the renderings that geometry.html.

Also I couldn't tell how to turn on the triangle lines (they seem to add some definition for what I am doing now) in the threeMeshIntersectExample.html and likewise I couldn't tell how to turn them off using the geometry.html style. It would be nice to have a check box for this.

**Comment by pboyer** [comment]
The mesh intersection example now shows clear lines. geometry.html is now out of date.
